Validation accuracy during training
facebookresearch/metaseq pull request #284
Opened 2022-08-02 20:49 UTC by ramakanth-pasunuru

- Tracks and plots validation accuracy for 2-way classification tasks during training
- Remove code owners for the opt_instruct branch

2022-08-03 21:38 UTC, stephenroller requested changes
Sorry Red flag

2022-08-03 21:38 UTC, stephenroller commented on metaseq/model_parallel/criterions/vocab_parallel_cross_entropy.py
> +        batch_loss = loss.mean(-1)
I don't think we want this. We're going to be dividing by n twice now I believe?

2022-08-25 19:54 UTC, sriniiyer commented
Did you do a before-after test? The train ppls are exactly the same before and after this PR, across muiltiple epochs?

2022-08-29 19:40 UTC, ramakanth-pasunuru commented
@sriniiyer Thanks for the suggestions. 
1. I checked that the train ppls remain the same for the whole training with and without this PR. 
2. I was able to match the reported accuracy during the training for valid set to be very close to the accuracy I got from gpt3_eval.py --> 47.4474 vs. 47.7477

2022-08-29 19:48 UTC, sriniiyer approved these changes
LGTM - This is awesome!

2022-08-29 20:59 UTC, merged